### ISSUE TITLE
Error starting the server on docker build

### ISSUE THREAD

**Issue by lnmunhoz** [decimals/sequence#5]
Hello, I just cloned your project, I wasn't able to pull the docker from github registry, so I changed the docker compose to build instead, not sure if all the configuration is there in order to build, but I got this error:

```sh
sequence_1  | Creating your server...
sequence_1  | Exception in thread "main" java.lang.RuntimeException: could not start [#'decimals.analytics/analytics] due to
sequence_1  | 	at mount.core$up$fn__14040.invoke(core.cljc:80)
```

<details>
   <summary>Click to expand full error </summary>

```
sequence_1  | Creating your server...
sequence_1  | Exception in thread "main" java.lang.RuntimeException: could not start [#'decimals.analytics/analytics] due to
sequence_1  | 	at mount.core$up$fn__14040.invoke(core.cljc:80)
sequence_1  | 	at mount.core$up.invokeStatic(core.cljc:80)
sequence_1  | 	at mount.core$up.invoke(core.cljc:78)
sequence_1  | 	at mount.core$bring.invokeStatic(core.cljc:247)
sequence_1  | 	at mount.core$bring.invoke(core.cljc:239)
sequence_1  | 	at mount.core$start.invokeStatic(core.cljc:289)
sequence_1  | 	at mount.core$start.doInvoke(core.cljc:281)
sequence_1  | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
sequence_1  | 	at decimals.transport$start.invokeStatic(transport.clj:24)
sequence_1  | 	at decimals.transport$start.invoke(transport.clj:23)
sequence_1  | 	at decimals.transport$_main.invokeStatic(transport.clj:31)
sequence_1  | 	at decimals.transport$_main.doInvoke(transport.clj:27)
sequence_1  | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
sequence_1  | 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
sequence_1  | 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
sequence_1  | 	at decimals.transport.main(Unknown Source)
sequence_1  | Caused by: java.lang.IllegalArgumentException: No matching field found: message for class java.lang.NullPointerException
sequence_1  | 	at clojure.lang.Reflector.getInstanceField(Reflector.java:397)
sequence_1  | 	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:440)
sequence_1  | 	at decimals.analytics$fn__21388.invokeStatic(analytics.clj:9)
sequence_1  | 	at decimals.analytics$fn__21388.invoke(analytics.clj:7)
sequence_1  | 	at mount.core$record_BANG_.invokeStatic(core.cljc:74)
sequence_1  | 	at mount.core$record_BANG_.invoke(core.cljc:73)
sequence_1  | 	at mount.core$up$fn__14040.invoke(core.cljc:81)
sequence_1  | 	... 15 more
sequence_sequence_1 exited with code 1
```
</details>

The only think I changed in the docker-compose file was:
```
services:
  sequence:
     build: .
     # image: docker.pkg.github.com/decimals/sequence/sequence:0.0.1
     # the rest is the same...
```

I haven't worked with clojure before so it's hard for me to debug. I assume it might be due I haven't provided the Segment.io key? Not sure but since is related to the `analytics` I think it could be an issue with that.

Happy to help debugging and looking forward to test this project :)

**Comment by andriosr** [comment]
Thanks, @lnmunhoz! I'm on it.

**Comment by andriosr** [comment]
@lnmunhoz can you confirm if the PR #6 is fixing the issue?

**Comment by lnmunhoz** [comment]
Seems like the server starts now 👍  Awesome, thanks!

But right now I am quite lost, I couldn't figure out how to see the api docs in the endpoint running. Could you invite me to your slack so we can discuss more about the project? (I tried trough the link in the website but I think the invite is required)

**Comment by andriosr** [comment]
Great. I'm inviting you and changing the invite to a form instead. It looks like Slack won't allow public access. Thanks for the heads up.

I will improve the docs. But the easiest way to start testing it is with the collections, using [Postman or Insomnia](https://docs.decimals.app/docs/sequence/docs/start-.md).

They are pointing to our servers. You need to change them to localhost:8910 and use the `123` API key to hit the local container.

I will add a local profile to them to make this easier.
